
---
- name: Installeer Nagios NRPE Server en configureer systeem
  hosts: jouw_servers
  become: yes
  tasks:
    - name: Installeer nagios-nrpe-server
      apt:
        name: nagios-nrpe-server
        state: present

    - name: Disable UFW
      command: ufw disable

    - name: Installeer Apache
      apt:
        name: apache2
        state: present

    - name: Installeer MySQL
      apt:
        name: mysql-server
        state: present

    - name: Installeer PHP en aanvullende modules
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysql
        - libapache2-mod-php
        - php-cli
        - php-cgi
        - php-gd
