- name: Installeer LAMP stack
  hosts: jouw_servers
  become: yes
  tasks:
    - name: Installeer Apache
      apt:
        name: apache2
        state: present

    - name: Installeer MySQL
      apt:
        name: mysql-server
        state: present

    - name: Installeer PHP en aanvullende modules
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysql
        - libapache2-mod-php
        - php-cli
        - php-cgi
        - php-gd
