---
- name: Maak Nagios configuratiebestanden voor myhosts
  hosts: myhosts
  become: yes
  tasks:
    - name: Maak een Nagios configuratiebestand
      template:
        src: /pad/naar/server_template.cfg.j2
        dest: "/etc/nagios4/objects/server{{ ansible_host.split('.')[-1] }}.cfg"
      delegate_to: localhost
