---
- name: apachehardening
  hosts: all
  become: yes
  tasks:
    - name: Update en upgrade
      apt:
        update_cache: yes
        upgrade: yes

    - name: install Apache
      apt:
        name: apache2
        state: present

    - name: Verwijder apache versie
      lineinfile:
        path: /etc/apache2/conf-available/security.conf
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - { regexp: '^ServerTokens OS', line: 'ServerTokens Prod' }
        - { regexp: '^ServerSignature On', line: 'ServerSignature Off' }

    - name: directorybrows
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^Options Indexes FollowSymLinks'
        line: 'Options FollowSymLinks'

    - name: SSL-module
      shell: |
        a2enmod ssl
        a2ensite default-ssl
        sed -i 's/SSLProtocol all -SSLv3/SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1/' /etc/apache2/mods-available/ssl.conf

    - name: HTTP-methoden
      blockinfile:
        path: /etc/apache2/apache2.conf
        block: |
          <Directory /var/www/>
          AllowOverride None
          Order allow,deny
          Allow from all
          <LimitExcept GET POST HEAD>
          deny from all
          </LimitExcept>
          </Directory>

    - name: ModSecurity
      shell: |
        apt-get install libapache2-mod-security2
        mv /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf
        sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/modsecurity/modsecurity.conf

    - name: restart Apache
      systemd:
        name: apache2
        state: restarted
