
---
- name: Installeer Nagios NRPE Server en configureer systeem
  hosts: all
  become: yes
  tasks:
    - name: Installeer nagios-nrpe-server
      apt:
        name: nagios-nrpe-server
        state: present

    - name: Disable UFW
      command: ufw disable
      
    - name: Sla het originele IP-adres op
      set_fact:
        original_ip: "{{ ansible_host }}"

    - name: Maak een Nagios configuratiebestand
      template:
        src: /home/masteruser/ansible_quickstart/server_template.cfg.j2
        dest: "/etc/nagios4/objects/server{{ original_ip.split('.')[-1] }}.cfg"
      delegate_to: localhost

    - name: voeg cfg_file regel toe aan config
      lineinfile: 
        path: /etc/nagios4/nagios.cfg
        line: "cfg_file=/etc/nagios4/objects/server{{ original_ip.split('.')[-1] }}.cfg"
        state: present
      delegate_to: localhost

    - name: Herstart Nagios4-service
      ansible.builtin.systemd:
        name: nagios4
        state: restarted
      delegate_to: localhost
