---
- hosts: jouw_wordpress_server
  become: yes
  vars:
    mysql_root_password: "jouw_mysql_root_wachtwoord"
    mysql_db: "wordpress"
    mysql_user: "wp_user"
    mysql_password: "wp_user_password"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installeer benodigde pakketten
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-cgi
          - php-gd
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Creëer MySQL Database
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
      become: yes
      become_user: root

    - name: Creëer MySQL Gebruiker
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
      become: yes
      become_user: root

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Pak WordPress uit in de webdirectory
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Configureer WordPress
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
